### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by spookey2008** [stvhwrd/SmoothStreamsTV-playlist#24]
![screenshot_20180930-183130_video player](https://user-images.githubusercontent.com/42916144/46260559-77b67f00-c4df-11e8-9920-758359f90dcb.jpg)
Hi could you help me with this please not sure what I've done wrong thanks

**Comment by stvhwrd** [comment]
Hi @spookey2008, I need some more information in order to help you.  It looks like your problem is with your Python installation from your picture.

What's the output of `python --version` and/or `python3 --version`?

Have you followed [the instructions](https://github.com/stvhwrd/SmoothStreamsTV-playlist#instructions)?

If you haven't made any changes, try removing the codebase you have and starting from scratch.

Please also show me how you are calling the script.  Copy/paste the output from your terminal, rather than taking a photo.

**Comment by spookey2008** [comment]
hi thanks for the reply im using python 3.5 im not sure why im getting the error. Please wait, generating playlist.
Traceback (most recent call last):
  File "/home/chris/Downloads/SmoothStreamsTV-playlist-master/sstv-playlist.py", line 490, in <module>
    main()
  File "/home/chris/Downloads/SmoothStreamsTV-playlist-master/sstv-playlist.py", line 130, in main
    authSign = getAuthSign(username, password, host)
  File "/home/chris/Downloads/SmoothStreamsTV-playlist-master/sstv-playlist.py", line 151, in getAuthSign
    response = urlopen(url).read().decode('utf-8')
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:

**Comment by stvhwrd** [comment]
I can't consistently replicate the issue.  There were a few other bugs that I've just fixed but none that seem related to your problem.  Can you please try the[ latest version](https://github.com/stvhwrd/SmoothStreamsTV-playlist/archive/master.zip) and let me know if it works for you?

**Comment by spookey2008** [comment]
thanks for the reply i have tryed a differnt server but same message

**Comment by stvhwrd** [comment]
The only way I can replicate this is when I use environment variables with invalid credentials (wrong password).  Are you using environment variables?  eg. running it with the `--env` or `-e` flag?

If not, please explain your process, start to finish.  Which operating system are you on?  Your screenshot is Windows and your pasted output appears to be Linux.  Are you using the latest version of the script?  If you don't provide me enough information, I can't help you.

**Comment by spookey2008** [comment]
Sorry think the fault is my end as I don't have a I'd or password any clue on how to get one thanks Chris
