### ISSUE TITLE
Windows 10 - Python 2.7

### ISSUE THREAD

**Issue by dbowles1975** [stvhwrd/SmoothStreamsTV-playlist#4]
Windows 10 / Python 2.7 - all goes well until it attempts to generate the playlist.

Thank you, generating playlist. 
[0m 
Traceback (most recent call last): 
File "./sstv-playlist.py", line 334, in <module>
 main() 
File "./sstv-playlist.py", line 74, in main playlistFile = buildPlaylistFile(playlistText) 
File "./sstv-playlist.py", line 141, in buildPlaylistFile call(['touch', title]) 
File "C:\Python27\lib\subprocess.py", line 523, in call return Popen(popenargs, *kwargs).wait() 
File "C:\Python27\lib\subprocess.py", line 711, in init errread, errwrite) 
File "C:\Python27\lib\subprocess.py", line 959, in _execute_child startupinfo) 
WindowsError: [Error 2] The system cannot find the file specified

**Comment by stvhwrd** [comment]
This was likely due to using an unneccessary Unix "touch" to create the file.  I've since removed the two system shell calls, which were really just hacks anyway.  Thanks @dbowles1975 for taking the time to test and provide feedback.
